# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c96b8a655e261d99850f9dc7a1603d0840c1f57fc7951a1eaa322a49516f1baff18b4214e1d0bbc8d6658d8df8fc8404ce9543facc76121db937e6beb387840

test:
  secret_key_base: d36f0a832bc8ad319e13ce83b958e7e7885575b6feeff3b7700ec0322992c4612b6578cf9a5b17cc93c80a82d7a776782f917f151f7132e3d95e312efe367ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
